/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.3
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchTransferCollectionItemsRequest
 */
export interface BatchTransferCollectionItemsRequest {
    /**
     * An array of valid EVM based addresses to transfer items to.
     * @type {Array<string>}
     * @memberof BatchTransferCollectionItemsRequest
     */
    addresses?: Array<string>;
    /**
     * An array of wallet ids within the MetaFab ecosystem to transfer items to.
     * @type {Array<string>}
     * @memberof BatchTransferCollectionItemsRequest
     */
    walletIds?: Array<string>;
    /**
     * An array of unique itemIds to transfer. Each recipient will receive the same set of items provided.
     * @type {Array<number>}
     * @memberof BatchTransferCollectionItemsRequest
     */
    itemIds: Array<number>;
    /**
     * The quantities of each unique itemId to transfer. Each recipient will receive the same quantities of items provided.
     * @type {Array<number>}
     * @memberof BatchTransferCollectionItemsRequest
     */
    quantities: Array<number>;
}

/**
 * Check if a given object implements the BatchTransferCollectionItemsRequest interface.
 */
export function instanceOfBatchTransferCollectionItemsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemIds" in value;
    isInstance = isInstance && "quantities" in value;

    return isInstance;
}

export function BatchTransferCollectionItemsRequestFromJSON(json: any): BatchTransferCollectionItemsRequest {
    return BatchTransferCollectionItemsRequestFromJSONTyped(json, false);
}

export function BatchTransferCollectionItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchTransferCollectionItemsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': !exists(json, 'addresses') ? undefined : json['addresses'],
        'walletIds': !exists(json, 'walletIds') ? undefined : json['walletIds'],
        'itemIds': json['itemIds'],
        'quantities': json['quantities'],
    };
}

export function BatchTransferCollectionItemsRequestToJSON(value?: BatchTransferCollectionItemsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': value.addresses,
        'walletIds': value.walletIds,
        'itemIds': value.itemIds,
        'quantities': value.quantities,
    };
}

