/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This field has not had a description added.
 * @export
 * @interface CollectionItemAttributesInnerValue
 */
export interface CollectionItemAttributesInnerValue {
}

/**
 * Check if a given object implements the CollectionItemAttributesInnerValue interface.
 */
export function instanceOfCollectionItemAttributesInnerValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CollectionItemAttributesInnerValueFromJSON(json: any): CollectionItemAttributesInnerValue {
    return CollectionItemAttributesInnerValueFromJSONTyped(json, false);
}

export function CollectionItemAttributesInnerValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionItemAttributesInnerValue {
    return json;
}

export function CollectionItemAttributesInnerValueToJSON(value?: CollectionItemAttributesInnerValue | null): any {
    return value;
}

