/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLootboxManagerRequest
 */
export interface CreateLootboxManagerRequest {
    /**
     * The name of this item collection. This can be anything, such as `Production - Lootbox Manager`, `Testing - My Game Lootbox Manager`, etc.
     * @type {string}
     * @memberof CreateLootboxManagerRequest
     */
    name?: string;
    /**
     * The blockchain you want to deploy this lootbox manager on. Support for new blockchains are added over time.
     * @type {string}
     * @memberof CreateLootboxManagerRequest
     */
    chain: CreateLootboxManagerRequestChainEnum;
}


/**
 * @export
 */
export const CreateLootboxManagerRequestChainEnum = {
    Arbitrum: 'ARBITRUM',
    Arbitrumgoerli: 'ARBITRUMGOERLI',
    Arbitrumnova: 'ARBITRUMNOVA',
    Avalanche: 'AVALANCHE',
    Avalanchefuji: 'AVALANCHEFUJI',
    Ethereum: 'ETHEREUM',
    Fantom: 'FANTOM',
    Fantomtest: 'FANTOMTEST',
    Goerli: 'GOERLI',
    Matic: 'MATIC',
    Maticmumbai: 'MATICMUMBAI',
    Thundercore: 'THUNDERCORE',
    Thundercoretestnet: 'THUNDERCORETESTNET'
} as const;
export type CreateLootboxManagerRequestChainEnum = typeof CreateLootboxManagerRequestChainEnum[keyof typeof CreateLootboxManagerRequestChainEnum];


/**
 * Check if a given object implements the CreateLootboxManagerRequest interface.
 */
export function instanceOfCreateLootboxManagerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chain" in value;

    return isInstance;
}

export function CreateLootboxManagerRequestFromJSON(json: any): CreateLootboxManagerRequest {
    return CreateLootboxManagerRequestFromJSONTyped(json, false);
}

export function CreateLootboxManagerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLootboxManagerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'chain': json['chain'],
    };
}

export function CreateLootboxManagerRequestToJSON(value?: CreateLootboxManagerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'chain': value.chain,
    };
}

