/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWalletSignatureRequest
 */
export interface CreateWalletSignatureRequest {
    /**
     * The plaintext message to sign.
     * @type {string}
     * @memberof CreateWalletSignatureRequest
     */
    message: string;
}

/**
 * Check if a given object implements the CreateWalletSignatureRequest interface.
 */
export function instanceOfCreateWalletSignatureRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateWalletSignatureRequestFromJSON(json: any): CreateWalletSignatureRequest {
    return CreateWalletSignatureRequestFromJSONTyped(json, false);
}

export function CreateWalletSignatureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWalletSignatureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function CreateWalletSignatureRequestToJSON(value?: CreateWalletSignatureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

