/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EcosystemGameModel
 */
export interface EcosystemGameModel {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof EcosystemGameModel
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof EcosystemGameModel
     */
    ecosystemId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof EcosystemGameModel
     */
    gameId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof EcosystemGameModel
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof EcosystemGameModel
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the EcosystemGameModel interface.
 */
export function instanceOfEcosystemGameModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EcosystemGameModelFromJSON(json: any): EcosystemGameModel {
    return EcosystemGameModelFromJSONTyped(json, false);
}

export function EcosystemGameModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EcosystemGameModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ecosystemId': !exists(json, 'ecosystemId') ? undefined : json['ecosystemId'],
        'gameId': !exists(json, 'gameId') ? undefined : json['gameId'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
    };
}

export function EcosystemGameModelToJSON(value?: EcosystemGameModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ecosystemId': value.ecosystemId,
        'gameId': value.gameId,
        'updatedAt': value.updatedAt,
        'createdAt': value.createdAt,
    };
}

