/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPlayerData200Response
 */
export interface GetPlayerData200Response {
    /**
     * 
     * @type {object}
     * @memberof GetPlayerData200Response
     */
    protectedData?: object;
    /**
     * 
     * @type {object}
     * @memberof GetPlayerData200Response
     */
    publicData?: object;
}

/**
 * Check if a given object implements the GetPlayerData200Response interface.
 */
export function instanceOfGetPlayerData200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPlayerData200ResponseFromJSON(json: any): GetPlayerData200Response {
    return GetPlayerData200ResponseFromJSONTyped(json, false);
}

export function GetPlayerData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayerData200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protectedData': !exists(json, 'protectedData') ? undefined : json['protectedData'],
        'publicData': !exists(json, 'publicData') ? undefined : json['publicData'],
    };
}

export function GetPlayerData200ResponseToJSON(value?: GetPlayerData200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protectedData': value.protectedData,
        'publicData': value.publicData,
    };
}

