/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MintCollectionItemRequest
 */
export interface MintCollectionItemRequest {
    /**
     * A valid EVM based address to create (mint) the item(s) for. For example, `0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D`.
     * @type {string}
     * @memberof MintCollectionItemRequest
     */
    address?: string;
    /**
     * The quantity of the specified item id to create (mint).
     * @type {number}
     * @memberof MintCollectionItemRequest
     */
    quantity: number;
    /**
     * Any wallet id within the MetaFab ecosystem to create (mint) the item(s) for.
     * @type {string}
     * @memberof MintCollectionItemRequest
     */
    walletId?: string;
}

/**
 * Check if a given object implements the MintCollectionItemRequest interface.
 */
export function instanceOfMintCollectionItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function MintCollectionItemRequestFromJSON(json: any): MintCollectionItemRequest {
    return MintCollectionItemRequestFromJSONTyped(json, false);
}

export function MintCollectionItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintCollectionItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'quantity': json['quantity'],
        'walletId': !exists(json, 'walletId') ? undefined : json['walletId'],
    };
}

export function MintCollectionItemRequestToJSON(value?: MintCollectionItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'quantity': value.quantity,
        'walletId': value.walletId,
    };
}

