/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublicPlayerCustodialWallet } from './PublicPlayerCustodialWallet';
import {
    PublicPlayerCustodialWalletFromJSON,
    PublicPlayerCustodialWalletFromJSONTyped,
    PublicPlayerCustodialWalletToJSON,
} from './PublicPlayerCustodialWallet';

/**
 * 
 * @export
 * @interface PublicProfile
 */
export interface PublicProfile {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicProfile
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicProfile
     */
    walletId?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicProfile
     */
    username?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicProfile
     */
    updatedAt?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicProfile
     */
    createdAt?: string;
    /**
     * 
     * @type {PublicPlayerCustodialWallet}
     * @memberof PublicProfile
     */
    custodialWallet?: PublicPlayerCustodialWallet;
    /**
     * 
     * @type {PublicPlayerCustodialWallet}
     * @memberof PublicProfile
     */
    wallet?: PublicPlayerCustodialWallet;
}

/**
 * Check if a given object implements the PublicProfile interface.
 */
export function instanceOfPublicProfile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicProfileFromJSON(json: any): PublicProfile {
    return PublicProfileFromJSONTyped(json, false);
}

export function PublicProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'walletId': !exists(json, 'walletId') ? undefined : json['walletId'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'custodialWallet': !exists(json, 'custodialWallet') ? undefined : PublicPlayerCustodialWalletFromJSON(json['custodialWallet']),
        'wallet': !exists(json, 'wallet') ? undefined : PublicPlayerCustodialWalletFromJSON(json['wallet']),
    };
}

export function PublicProfileToJSON(value?: PublicProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'walletId': value.walletId,
        'username': value.username,
        'updatedAt': value.updatedAt,
        'createdAt': value.createdAt,
        'custodialWallet': PublicPlayerCustodialWalletToJSON(value.custodialWallet),
        'wallet': PublicPlayerCustodialWalletToJSON(value.wallet),
    };
}

