/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPlayerCustodialWallet
 */
export interface PublicPlayerCustodialWallet {
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicPlayerCustodialWallet
     */
    id?: string;
    /**
     * This field has not had a description added.
     * @type {string}
     * @memberof PublicPlayerCustodialWallet
     */
    address?: string;
}

/**
 * Check if a given object implements the PublicPlayerCustodialWallet interface.
 */
export function instanceOfPublicPlayerCustodialWallet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicPlayerCustodialWalletFromJSON(json: any): PublicPlayerCustodialWallet {
    return PublicPlayerCustodialWalletFromJSONTyped(json, false);
}

export function PublicPlayerCustodialWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPlayerCustodialWallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function PublicPlayerCustodialWalletToJSON(value?: PublicPlayerCustodialWallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'address': value.address,
    };
}

