/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetLootboxManagerLootboxRequest
 */
export interface SetLootboxManagerLootboxRequest {
    /**
     * A unique lootbox id to use for this lootbox for the lootbox manager. If an existing lootbox id is used, the current lootbox will be updated but the existing number of opens will be kept. If you want to reset the number of opens for an existing lootbox, first remove it using the remove lootbox endpoint, then set it.
     * @type {number}
     * @memberof SetLootboxManagerLootboxRequest
     */
    id: number;
    /**
     * A valid EVM based ERC1155 or MetaFab game items contract address that represents the collection for input items required by this lootbox. `inputCollectionAddress` or `inputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetLootboxManagerLootboxRequest
     */
    inputCollectionAddress?: string;
    /**
     * A valid MetaFab collection id that represents the collection for input items required by this lootbox. `inputCollectionAddress` or `inputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetLootboxManagerLootboxRequest
     */
    inputCollectionId?: string;
    /**
     * An array of item ids from the provided input collection that are required to open this lootbox. Input items are burn upon opening a lootbox.
     * @type {Array<number>}
     * @memberof SetLootboxManagerLootboxRequest
     */
    inputCollectionItemIds?: Array<number>;
    /**
     * An array of amounts for each item id from the provided input collection that are required to open this lootbox. Item amounts array indices are reflective of the amount required for a given item id at the same index.
     * @type {Array<number>}
     * @memberof SetLootboxManagerLootboxRequest
     */
    inputCollectionItemAmounts?: Array<number>;
    /**
     * A valid EVM based ERC1155 or MetaFab game items contract address that represents the collection for possible output items given by this lootbox. `outputCollectionAddress` or `outputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputCollectionAddress?: string;
    /**
     * A valid MetaFab collection id that represents the collection for possible output items given by this lootbox. `outputCollectionAddress` or `outputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputCollectionId?: string;
    /**
     * An array of item ids from the provided output collection that are possibly given by this lootbox. Randomly selected output items are automatically minted if the lootbox manager contract has the `minter` role for the output collection contract. Otherwise, they are transferred from the item balance held by the lootbox manager contract.
     * @type {Array<number>}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputCollectionItemIds?: Array<number>;
    /**
     * An array of amounts for each item id that can be randomly selected from the provided output collection that are given by this lootbox. Item amounts array indices are reflective of the amount required for a given item id at the same index.
     * @type {Array<number>}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputCollectionItemAmounts?: Array<number>;
    /**
     * An array of weights for each item id that can be randomly selected from the provided output collection that are given by this lootbox. Any positive integer for an item's weight can be provided. The weight for an item relative to the sum of all possible item weights determines the probability that an item will be picked upon a lootbox being opened. Item weights array indices are reflective of the probability weight for a given item id at the same index.
     * @type {Array<number>}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputCollectionItemWeights?: Array<number>;
    /**
     * The number of items randomly selected from the possible output items when this lootbox is open. If you provide a value greater than 1, it is possible for the same item to be selected more than once, giving the opener more than one of that item's output from the lootbox.
     * @type {number}
     * @memberof SetLootboxManagerLootboxRequest
     */
    outputTotalItems?: number;
}

/**
 * Check if a given object implements the SetLootboxManagerLootboxRequest interface.
 */
export function instanceOfSetLootboxManagerLootboxRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SetLootboxManagerLootboxRequestFromJSON(json: any): SetLootboxManagerLootboxRequest {
    return SetLootboxManagerLootboxRequestFromJSONTyped(json, false);
}

export function SetLootboxManagerLootboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetLootboxManagerLootboxRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inputCollectionAddress': !exists(json, 'inputCollectionAddress') ? undefined : json['inputCollectionAddress'],
        'inputCollectionId': !exists(json, 'inputCollectionId') ? undefined : json['inputCollectionId'],
        'inputCollectionItemIds': !exists(json, 'inputCollectionItemIds') ? undefined : json['inputCollectionItemIds'],
        'inputCollectionItemAmounts': !exists(json, 'inputCollectionItemAmounts') ? undefined : json['inputCollectionItemAmounts'],
        'outputCollectionAddress': !exists(json, 'outputCollectionAddress') ? undefined : json['outputCollectionAddress'],
        'outputCollectionId': !exists(json, 'outputCollectionId') ? undefined : json['outputCollectionId'],
        'outputCollectionItemIds': !exists(json, 'outputCollectionItemIds') ? undefined : json['outputCollectionItemIds'],
        'outputCollectionItemAmounts': !exists(json, 'outputCollectionItemAmounts') ? undefined : json['outputCollectionItemAmounts'],
        'outputCollectionItemWeights': !exists(json, 'outputCollectionItemWeights') ? undefined : json['outputCollectionItemWeights'],
        'outputTotalItems': !exists(json, 'outputTotalItems') ? undefined : json['outputTotalItems'],
    };
}

export function SetLootboxManagerLootboxRequestToJSON(value?: SetLootboxManagerLootboxRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'inputCollectionAddress': value.inputCollectionAddress,
        'inputCollectionId': value.inputCollectionId,
        'inputCollectionItemIds': value.inputCollectionItemIds,
        'inputCollectionItemAmounts': value.inputCollectionItemAmounts,
        'outputCollectionAddress': value.outputCollectionAddress,
        'outputCollectionId': value.outputCollectionId,
        'outputCollectionItemIds': value.outputCollectionItemIds,
        'outputCollectionItemAmounts': value.outputCollectionItemAmounts,
        'outputCollectionItemWeights': value.outputCollectionItemWeights,
        'outputTotalItems': value.outputTotalItems,
    };
}

