/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetShopOfferRequest
 */
export interface SetShopOfferRequest {
    /**
     * A unique offer id to use for this offer for the shop. If an existing offer id is used, the current offer will be updated but the existing number of uses will be kept. If you want to reset the number of uses for an existing offer, first remove it using the remove offer endpoint, then set it.
     * @type {number}
     * @memberof SetShopOfferRequest
     */
    id: number;
    /**
     * A valid EVM based ERC1155 or MetaFab game items contract address that represents the collection for input items required by this offer. `inputCollectionAddress` or `inputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    inputCollectionAddress?: string;
    /**
     * A valid MetaFab collection id that represents the collection for input items required by this offer. `inputCollectionAddress` or `inputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    inputCollectionId?: string;
    /**
     * An array of item ids from the provided input collection that are required to use this offer. Input items are transferred from the wallet to the shop contract upon using an offer.
     * @type {Array<number>}
     * @memberof SetShopOfferRequest
     */
    inputCollectionItemIds?: Array<number>;
    /**
     * An array of amounts for each item id from the provided input collection that are required to use this offer. Item amounts array indices are reflective of the amount required for a given item id at the same index.
     * @type {Array<number>}
     * @memberof SetShopOfferRequest
     */
    inputCollectionItemAmounts?: Array<number>;
    /**
     * A valid EVM based ERC20 or MetaFab game currency contract address that for the currency required by this offer.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    inputCurrencyAddress?: string;
    /**
     * A valid MetaFab currency id that represents the currency required by this offer.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    inputCurrencyId?: string;
    /**
     * The amount of currency required by this offer. If an inputCurrencyAmount is provided without in input currency address or id, the native chain currency is used as the required currency.
     * @type {number}
     * @memberof SetShopOfferRequest
     */
    inputCurrencyAmount?: number;
    /**
     * A valid EVM based ERC1155 or MetaFab game items contract address that represents the collection for output items given by this offer. `outputCollectionAddress` or `outputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    outputCollectionAddress?: string;
    /**
     * A valid MetaFab collection id that represents the collection for output items given by this offer. `outputCollectionAddress` or `outputCollectionId` can optionally be provided.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    outputCollectionId?: string;
    /**
     * An array of item ids from the provided output collection that are given by this offer. Output items are automatically minted if the shop contract has the `minter` role for the output collection contract. Otherwise, they are transferred from the item balance held by the shop contract.
     * @type {Array<number>}
     * @memberof SetShopOfferRequest
     */
    outputCollectionItemIds?: Array<number>;
    /**
     * An array of amounts for each item id from the provided output collection that are given by this offer. Item amounts array indices are reflective of the amount required for a given item id at the same index.
     * @type {Array<number>}
     * @memberof SetShopOfferRequest
     */
    outputCollectionItemAmounts?: Array<number>;
    /**
     * A valid EVM based ERC20 or MetaFab game currency contract address that for the currency given by this offer. The output currency amount is automatically minted if the shop contract has the `minter` role for the output currency contract. Otherwise, they are transferred from the currency balance held by the shop contract.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    outputCurrencyAddress?: string;
    /**
     * A valid MetaFab currency id for the currency given by this offer.
     * @type {string}
     * @memberof SetShopOfferRequest
     */
    outputCurrencyId?: string;
    /**
     * The amount of currency given by this offer. If an outputCurrencyAmount is provided without an output currency address or id, the native chain currency is used as the given currency.
     * @type {number}
     * @memberof SetShopOfferRequest
     */
    outputCurrencyAmount?: number;
    /**
     * The maximum number of times this offer can be used in total. maxUses is collective across all uses of the offer. If 5 unique players use an offer, that counts as 5 offer uses. Exclude this or use 0 to allow unlimited uses.
     * @type {number}
     * @memberof SetShopOfferRequest
     */
    maxUses?: number;
}

/**
 * Check if a given object implements the SetShopOfferRequest interface.
 */
export function instanceOfSetShopOfferRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SetShopOfferRequestFromJSON(json: any): SetShopOfferRequest {
    return SetShopOfferRequestFromJSONTyped(json, false);
}

export function SetShopOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetShopOfferRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inputCollectionAddress': !exists(json, 'inputCollectionAddress') ? undefined : json['inputCollectionAddress'],
        'inputCollectionId': !exists(json, 'inputCollectionId') ? undefined : json['inputCollectionId'],
        'inputCollectionItemIds': !exists(json, 'inputCollectionItemIds') ? undefined : json['inputCollectionItemIds'],
        'inputCollectionItemAmounts': !exists(json, 'inputCollectionItemAmounts') ? undefined : json['inputCollectionItemAmounts'],
        'inputCurrencyAddress': !exists(json, 'inputCurrencyAddress') ? undefined : json['inputCurrencyAddress'],
        'inputCurrencyId': !exists(json, 'inputCurrencyId') ? undefined : json['inputCurrencyId'],
        'inputCurrencyAmount': !exists(json, 'inputCurrencyAmount') ? undefined : json['inputCurrencyAmount'],
        'outputCollectionAddress': !exists(json, 'outputCollectionAddress') ? undefined : json['outputCollectionAddress'],
        'outputCollectionId': !exists(json, 'outputCollectionId') ? undefined : json['outputCollectionId'],
        'outputCollectionItemIds': !exists(json, 'outputCollectionItemIds') ? undefined : json['outputCollectionItemIds'],
        'outputCollectionItemAmounts': !exists(json, 'outputCollectionItemAmounts') ? undefined : json['outputCollectionItemAmounts'],
        'outputCurrencyAddress': !exists(json, 'outputCurrencyAddress') ? undefined : json['outputCurrencyAddress'],
        'outputCurrencyId': !exists(json, 'outputCurrencyId') ? undefined : json['outputCurrencyId'],
        'outputCurrencyAmount': !exists(json, 'outputCurrencyAmount') ? undefined : json['outputCurrencyAmount'],
        'maxUses': !exists(json, 'maxUses') ? undefined : json['maxUses'],
    };
}

export function SetShopOfferRequestToJSON(value?: SetShopOfferRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'inputCollectionAddress': value.inputCollectionAddress,
        'inputCollectionId': value.inputCollectionId,
        'inputCollectionItemIds': value.inputCollectionItemIds,
        'inputCollectionItemAmounts': value.inputCollectionItemAmounts,
        'inputCurrencyAddress': value.inputCurrencyAddress,
        'inputCurrencyId': value.inputCurrencyId,
        'inputCurrencyAmount': value.inputCurrencyAmount,
        'outputCollectionAddress': value.outputCollectionAddress,
        'outputCollectionId': value.outputCollectionId,
        'outputCollectionItemIds': value.outputCollectionItemIds,
        'outputCollectionItemAmounts': value.outputCollectionItemAmounts,
        'outputCurrencyAddress': value.outputCurrencyAddress,
        'outputCurrencyId': value.outputCurrencyId,
        'outputCurrencyAmount': value.outputCurrencyAmount,
        'maxUses': value.maxUses,
    };
}

