/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.3
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferCurrencyRequest
 */
export interface TransferCurrencyRequest {
    /**
     * A valid EVM based address to transfer currency to. For example, `0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D`.
     * @type {string}
     * @memberof TransferCurrencyRequest
     */
    address?: string;
    /**
     * Any wallet id within the MetaFab ecosystem to transfer currency to.
     * @type {string}
     * @memberof TransferCurrencyRequest
     */
    walletId?: string;
    /**
     * The amount of currency to transfer.
     * @type {number}
     * @memberof TransferCurrencyRequest
     */
    amount: number;
    /**
     * An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services.
     * @type {number}
     * @memberof TransferCurrencyRequest
     */
    reference?: number;
}

/**
 * Check if a given object implements the TransferCurrencyRequest interface.
 */
export function instanceOfTransferCurrencyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function TransferCurrencyRequestFromJSON(json: any): TransferCurrencyRequest {
    return TransferCurrencyRequestFromJSONTyped(json, false);
}

export function TransferCurrencyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferCurrencyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'walletId': !exists(json, 'walletId') ? undefined : json['walletId'],
        'amount': json['amount'],
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
    };
}

export function TransferCurrencyRequestToJSON(value?: TransferCurrencyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'walletId': value.walletId,
        'amount': value.amount,
        'reference': value.reference,
    };
}

