/* tslint:disable */
/* eslint-disable */
/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteContractRequestArgsInner
 */
export interface WriteContractRequestArgsInner {
}

/**
 * Check if a given object implements the WriteContractRequestArgsInner interface.
 */
export function instanceOfWriteContractRequestArgsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WriteContractRequestArgsInnerFromJSON(json: any): WriteContractRequestArgsInner {
    return WriteContractRequestArgsInnerFromJSONTyped(json, false);
}

export function WriteContractRequestArgsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteContractRequestArgsInner {
    return json;
}

export function WriteContractRequestArgsInnerToJSON(value?: WriteContractRequestArgsInner | null): any {
    return value;
}

